---

url:         http://masterplan.opensensorsdata.it
## baseurl:     /
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:year/:month/:day/:title/
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Masterplan // Build it to share!!"
keywords:    "project, opendata, open business model, condivisione, riuso"
description: "Il Masterplan è un modello concettuale per armonizzare obiettivi di business, organizzazione dei ruoli e condivisione di dati."
source_link: "https://github.com/opensensorsdata/masterplan"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.jpg"
google_analytics_key:  UA-72246976-1

## Author
author:
  name:           'osd crew'
  url:            'https://twitter.com/osd_it'
  twitter:        'osd_it'
  facebook:       'https://www.facebook.com/opensensorsdata'
  mail:           'contact@opensensorsdata.it'


### social profile
social:
  github:           https://github.com/opensensorsdata/
  twitter:          https://twitter.com/osd_it
  facebook:         https://www.facebook.com/opensensorsdata
  medium:           https://medium.com/opensensorsdata-review

### Site version
version:     '1'
last-revision: '2015-12-15'


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  # osd colours
  osd-blue:      '#002fa7'
  osd-purple:    '#ea5480'
  # Goethe https://commons.wikimedia.org/wiki/File:Qubodup-GoetheFarbkreis_en.svg
  rosso:     'rgba(210,15,33,0.7)'
  arancio:   'rgba(250,71,11,0.7)'
  giallo:    'rgba(255,203,8,0.7)'
  verde:     'rgba(3,140,38,0.7)'
  ciano:     'rgba(22,166,234,0.7)'
  blu:       'rgba(14,65,111,0.7)'

  #rosso:     '#d20f21'
  #arancio:   '#fa470b'
  #giallo:    '#ffcb08'
  #verde:     '#038c26'
  #ciano:     '#16a6ea'
  #blu:       '#0e416f'
  # Chevreul Colorwheel https://it.wikipedia.org/wiki/File:Rgb-colorwheel.svg
  1:         '#ff00ff'
  2:         '#8000ff'
  3:         '#0000ff'
  4:         '#0080ff'
  5:         '#00ffff'
  6:         '#00ff80'
  7:         '#00ff00'
  8:         '#80ff00'
  9:         '#ffff00'
  10:        '#ff8000'
  11:        '#ff0000'
  12:        '#ff0080'


kramdown:
  auto_ids:  false

